# Generated by Django 3.2.11 on 2024-05-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_alter_usersetting_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
