# Generated by Django 3.2.11 on 2022-08-29 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='giving_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giving_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='receiving_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
