# Generated by Django 3.2.11 on 2024-03-15 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relations', '0002_auto_20220829_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1_giving_ticket_img', models.CharField(max_length=13)),
                ('user_2_giving_ticket_img', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
