# Generated by Django 3.2.11 on 2024-03-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0003_userrelation2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrelation',
            table='user_relations_userrelation_old',
        ),
        migrations.AlterModelTable(
            name='userrelation2',
            table='user_relations_userrelation',
        ),
    ]
