# Generated by Django 3.2.11 on 2024-03-15 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20240315_1151'),
        ('diaries', '0006_auto_20240315_1151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relations', '0004_auto_20240315_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRelation',
            new_name='UserRelationOld',
        ),
    ]
