# Generated by Django 3.2.11 on 2024-03-15 12:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20240315_1151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diaries', '0006_auto_20240315_1151'),
        ('user_relations', '0005_rename_userrelation_userrelationold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRelation2',
            new_name='UserRelation',
        ),
    ]
