# Generated by Django 3.2.11 on 2024-03-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0006_rename_userrelation2_userrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRelationOld',
        ),
    ]
