# Generated by Django 3.2.11 on 2024-05-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0007_delete_userrelationold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='user_1_giving_ticket_img',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='user_2_giving_ticket_img',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
