# Generated by Django 3.2.11 on 2024-05-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0008_auto_20240510_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelation',
            name='use_slack',
            field=models.BooleanField(default=False),
        ),
    ]
