# Generated by Django 3.2.11 on 2023-12-21 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0002_auto_20220829_0615'),
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
                ('sort_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_relations.userrelation')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryTagRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.diary')),
                ('tag_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.diarytag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='diarytag',
            constraint=models.UniqueConstraint(fields=('text', 'user_relation'), name='unique_text_user_relation'),
        ),
        migrations.AddConstraint(
            model_name='diarytag',
            constraint=models.UniqueConstraint(fields=('sort_no', 'user_relation'), name='unique_sort_no_user_relation'),
        ),
    ]
