# Generated by Django 3.2.11 on 2024-01-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_diary_tags'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diarytag',
            name='unique_text_user_relation',
        ),
        migrations.RemoveConstraint(
            model_name='diarytag',
            name='unique_sort_no_user_relation',
        ),
    ]
