# Generated by Django 3.2.11 on 2024-01-31 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_auto_20240111_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarytagrelation',
            name='tag_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diaries.diarytag'),
        ),
    ]
