# Generated by Django 3.2.11 on 2024-03-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0003_userrelation2'),
        ('diaries', '0005_alter_diarytagrelation_tag_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user_relation_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_relations.userrelation2'),
        ),
        migrations.AddField(
            model_name='diarytag',
            name='user_relation_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_relations.userrelation2'),
        ),
    ]
