# Generated by Django 3.2.11 on 2024-03-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_auto_20240315_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='user_relation',
            new_name='user_relation_old',
        ),
        migrations.RenameField(
            model_name='diarytag',
            old_name='user_relation',
            new_name='user_relation_old',
        ),
    ]
