# Generated by Django 3.2.11 on 2024-03-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_auto_20240315_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='user_relation_2',
            new_name='user_relation',
        ),
        migrations.RenameField(
            model_name='diarytag',
            old_name='user_relation_2',
            new_name='user_relation',
        ),
    ]
