# Generated by Django 3.2.11 on 2024-03-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0006_rename_userrelation2_userrelation'),
        ('diaries', '0009_auto_20240317_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='user_relation_old',
        ),
        migrations.RemoveField(
            model_name='diarytag',
            name='user_relation_old',
        ),
        migrations.AlterField(
            model_name='diary',
            name='user_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_relations.userrelation'),
        ),
        migrations.AlterField(
            model_name='diarytag',
            name='user_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_relations.userrelation'),
        ),
    ]
