# Generated by Django 3.2.11 on 2024-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0010_auto_20240319_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user_1_status',
            field=models.CharField(choices=[('unread', 'unread'), ('edited', 'edited'), ('read', 'read')], default='unread', max_length=8),
        ),
        migrations.AddField(
            model_name='diary',
            name='user_2_status',
            field=models.CharField(choices=[('unread', 'unread'), ('edited', 'edited'), ('read', 'read')], default='unread', max_length=8),
        ),
    ]
