# Generated by Django 3.2.11 on 2022-07-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('gift_date', models.DateTimeField()),
                ('use_description', models.TextField(blank=True, default='')),
                ('use_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('unread', 'unread'), ('read', 'read'), ('edited', 'edited'), ('draft', 'draft')], max_length=8)),
                ('is_special', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_relations.userrelation')),
            ],
        ),
    ]
