# Generated by Django 3.2.11 on 2022-07-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='gift_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='use_date',
            field=models.DateField(null=True),
        ),
    ]
