# Generated by Django 3.2.11 on 2024-03-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_user_relation_ticket_user_relation_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_relation_2',
            new_name='user_relation',
        ),
    ]
