# Generated by Django 3.2.11 on 2024-03-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0006_rename_userrelation2_userrelation'),
        ('tickets', '0006_rename_user_relation_2_ticket_user_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_relation_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_relations.userrelationold'),
        ),
    ]
